# bonjour.yml
name: Bonjour
on:
  - push
jobs:
  livraison_continue:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "mynode:19"
    steps:
      - uses: actions/checkout@v3 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - run: npm install
      - run: npm run lint
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: moshtek
          password: ${{ secrets.DOCKERHUB_CD }}
      - name: Push if on `main`
        uses: docker/build-push-action@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          context: ./
          tags: moshtek/sayhello:1.0.6
      - run: cat README.md